---
abstract: 'Perl extension for the Net::Hulu name space.  Can be use to download'
author:
  - 'Gerald L. Hevener, M.S. <{[hevenerg]}at{[marshall]}dot{[edu]}>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Distribution: 2.00
  Test::Kwalitee: 1.01
  Test::More: 0.94
  Test::Perl::Critic: 1.02
  Test::Pod: 1.40
  Test::Pod::Coverage: 1.08
  Test::Strict: 0.13
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Hulu
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.11
  LWP::Simple: 2.18
  XML::Twig: 3.32
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
